import _TriangleArrow from "./components/generic/triangleArrow/TriangleArrow";
import _Mudgun from "./components/industry/mudgun/Mudgun";
import _EafFurnace from "./components/industry/eaf-furnace/EafFurnace";
import _BlastFurnace from "./components/industry/blast-furnace/BlastFurnace";
import _DryFurnace from "./components/industry/dry-furnace/DryFurnace";
import _AppIcon from "./components/wrappers/app-icon/AppIcon";
import _MainRunnerSlice from "./components/industry/main-runner-slice/MainRunnerSlice";
import _TemperatureMeasure from "./components/industry/temperature-measure/TemperatureMeasure";
import _WorkSite from "./components/industry/work-site/WorkSite";
import _CameraIr from "./components/industry/camera-ir/CameraIr";
import _MainRunnerTemperature from "./components/industry/main-runner-temperature/MainRunnerTemperature";
import _TiltRunner from "./components/industry/tilt-runner/TiltRunner";
import _PrecastWorkout from "./components/industry/precast-workout/PrecastWorkout";
import _VibratingCast from "./components/industry/vibrating-cast/VibratingCast";
import _Tamping from "./components/industry/tamping/Tamping";
import _DenseGuning from "./components/industry/dense-guning/DenseGuning";
import _FineGuning from "./components/industry/fine-guning/FineGuning";
import _MainRunnerCasting from "./components/industry/main-runner-casting/MainRunnerCasting";
import _MainRunnerTop from "./components/industry/main-runner-top/MainRunnerTop";

export const TriangleArrow = _TriangleArrow;
export const Mudgun = _Mudgun;
export const EafFurnace = _EafFurnace;
export const BlastFurnace = _BlastFurnace;
export const DryFurnace = _DryFurnace;
export const MainRunnerSlice = _MainRunnerSlice;
export const TemperatureMeasure = _TemperatureMeasure;
export const WorkSite = _WorkSite;
export const AppIcon = _AppIcon;
export const CameraIr = _CameraIr;
export const MainRunnerTemperature = _MainRunnerTemperature;
export const TiltRunner = _TiltRunner;
export const PrecastWorkout = _PrecastWorkout;
export const VibratingCast = _VibratingCast;
export const Tamping = _Tamping;
export const DenseGuning = _DenseGuning;
export const FineGuning = _FineGuning;
export const MainRunnerCasting = _MainRunnerCasting;
export const MainRunnerTop = _MainRunnerTop;
